dtolnay/serde-yaml

.travis.yml, Cargo.toml, scripts/build.sh
The main caveat of this pull request is tests for stable and beta cannot be run due to relying on `serde_marco`, it might be worth looking into how the [serde/json](https://github.com/serde-rs/json) run their tests for stable and beta.
Solves Issue #1
=> Build with rust stable and beta

yaml/Cargo.toml
This is blocked on the following PRs and releases:
=> Preserve order of map keys

yaml/src/error.rs, yaml_tests/tests/test_error.rs
=> Formatted error messages created by other libraries no longer get overridden

yaml/src/de.rs, yaml/src/error.rs, yaml/src/lib.rs, yaml/src/path.rs, yaml_tests/tests/test_error.rs
Fixes #42. cc https://github.com/jwilm/alacritty/issues/359
```yaml
b:
- C:
d: fale
```
> b[0].C.d: invalid type: string "fale", expected a boolean at line 3 column 10
=> Track path to errors

yaml/src/lib.rs, yaml/src/mapping.rs, yaml/src/value.rs, yaml_tests/tests/test_de.rs, yaml_tests/tests/test_serde.rs
Fixes #46.
There are a couple of things that might be interesting to think about here before merging:
- Mapping isn't fully compatible with LinkedHashMap. In some cases, this is intentional: e.g. by not implementing pop_front() and pop_back() we retain the flexibility to switch to another non-ordered map implementation in the future. But, this does mean that serde-yaml users may need to modify their code after this change.
- We're still leaking some parts of the linked_hash_map API (e.g., iterator types).
- Maybe we should move Mapping to "mapping.rs" instead, to avoid polluting value.rs with a bunch of boilerplate?
=> Implement {S,Des}erialize for Mapping

src/lib.rs, src/value.rs
Inspired by¹ the serde_json docs.
~~Rustdoc gave me some warnings that only the first code block of each doc string was actually being tested, so I put everything in one code block by shadowing the value binding.~~ This is rust-lang/rust#41401, but it only affects recent nightlies.
¹ I.e., copypasta from
=> Add a bunch of docs

src/lib.rs, src/value/de.rs, src/value/from.rs, src/value/index.rs, src/value/mod.rs, src/value/number.rs, src/value/partial_eq.rs, src/value/ser.rs, tests/test_serde.rs
Copies the `Number` type from `serde_json` and converts this project to use it. Known issue compiling a hash function.
Closes: #60
=> Hide numeric types

src/de.rs, tests/test_de.rs
- Explicitly consider aliases in deserialize_str
- Add a test case that failed before, and works afterwards
Closes dtolnay/serde-yaml#70
=> Allow aliases to scalars to be deserialized as strings

Cargo.toml, tests/version-numbers.rs
This adds an integration test which will fail if the README and `lib.rs` files don't mention the correct crate version number.
=> Ensure that version numbers are in sync with crate version

tests/test_visitor.rs
It seems that there is some kind of implementation difference between `deserialize_str` and `deserialize_string`
This adds the failing `test_visitor` test, which is an almost exact replica of the "string or struct" example in the [serde guide](https://serde.rs/string-or-struct.html) (except it is "string or list").
```
running 1 test
test test_visitor ... FAILED
thread 'test_visitor' panicked at 'didn't deserialize: Message("invalid type: string \"foo\", expected a borrowed string", Some(Pos { marker: Marker { index: 7, line: 3, col: 2 }, path: ".[0]" }))', /checkout/src/libcore/result.rs:906:4
```
The issue is in the `FIXME` comments. Changing from `::<&str>` -> `::<String>` in the visitor code fixes the test (but that shouldn't be required).
=> add failing and ignored test_visitor test

Cargo.toml, src/de.rs, src/lib.rs, tests/test_serde.rs
As yaml-rust 0.4 got publisched on crates.io recently, it would be nice to use it for serde-yaml. There are some some fixes (especially for the emitter) I'd really like use with serde.
=> Use yaml-rust 0.4

Cargo.toml, src/de.rs, tests/test_serde.rs
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
---
Some tests are still failing, so help is very welcomed (probably those are bugs in yaml-rust)..
```rust
---- test_basic_struct stdout ----
thread 'test_basic_struct' panicked at 'assertion failed: `(left == right)`
left: `"---\nx: -4\ny: \"hi\\tquoted\"\nz: true"`,
right: `"---\nx: -4\n\"y\": \"hi\\tquoted\"\nz: true"`', tests/test_serde.rs:27:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
---- test_map stdout ----
thread 'test_map' panicked at 'assertion failed: `(left == right)`
left: `"---\nx: 1\ny: 2"`,
right: `"---\nx: 1\n\"y\": 2"`', tests/test_serde.rs:27:4
---- test_nested_vec stdout ----
thread 'test_nested_vec' panicked at 'assertion failed: `(left == right)`
left: `"---\n-\n  - 1\n  - 2\n  - 3\n-\n  - 4\n  - …
```
=> bump yaml-rust to 0.4

src/de.rs, tests/test_error.rs
=> Fix panic in invalid_type

src/de.rs, src/error.rs, tests/test_error.rs
Depends on https://github.com/chyh1990/yaml-rust/pull/109 to work
=> Prevent too deep recursion

src/value/mod.rs, tests/test_serde.rs
Fixes #119 
This PR defines a default value for `serde_yaml::Value` struct.
=> Add Default implementation for Value

src/value/partial_eq.rs
The comparison of unsigned integers as `i64` was last touched in #62 (Apr 21, 2017) and `as_u64` as added in #64 (Apr 25, 2017), explaining why the unsigned integers didn't compare as `u64` in the first place.
=> Value == u64

src/value/partial_eq.rs
`Number` and `String` values can be compared, so why not `Bool`?
=> Value == bool

src/de.rs, src/lib.rs, tests/test_de.rs
Allows usage of `DeserializeSeed` types.
The `T` parameters on `_seed` functions are required because it's not possible to extract `S::Value` out of the higher-rank bound without also specifying that for all `'de`, `S::Value` is indeed the same type.
=> Add seeded versions of deserialize functions.

.travis.yml
Previously, it would run on the most recent nightly always, and simply skip Clippy if it wasn't available in that nightly.
=> Run clippy on latest nightly that has clippy

src/number.rs, tests/test_value.rs
There is only `.nan` and `-.nan`. Update the PartialEq impl for Value to align with this; for example we shouldn't allow building a YAML map with multiple `.nan` keys having different bit representations.
=> YAML only has two NaNs

src/de.rs, src/number.rs, tests/test_value.rs
Upon closer inspection of #156, we were incorrectly producing negative nans (and also infinities) through f64::from_str which were not supposed to be YAML nans or infinities.
=> Only accept finite values from f64::from_str

README.md
Closes #161. This has been broken since #88.
=> Update readme code samples to not fail assert

Cargo.toml
linked_hashmap has an unsound behaviour which was fixed 0.5.3. Bumping the dependency so that dependents do not pull the lower unsound versions based on resolution. 
[Advisory](https://github.com/RustSec/advisory-db/issues/298)
Side note: yaml_rust is affected as well ([pr] https://github.com/chyh1990/yaml-rust/pull/162) so that dependency will have to be updated when they release as well.
=> bump linked hashmap to min 0.5.3

src/de.rs, tests/test_value.rs
Closes #179.
According to the YAML 1.2 spec (https://yaml.org/spec/1.2/spec.html#id2761292) numbers sequences with a leading zeros (that are not special encoding identifiers such as 0x, 0b, etc) are actually strings.
This patch handles this case, all existing tests still pass.
=> Add a check for strings disguised as leading zeros followed by numbers

src/lib.rs, src/ser.rs, src/value/mod.rs
```rust
use anyhow::Result;
use serde::Serialize;
use std::collections::BTreeMap;
fn main() -> Result<()> {
let mut buffer = Vec::new();
let mut ser = serde_yaml::Serializer::new(&mut buffer);
let mut object = BTreeMap::new();
object.insert("k", 107);
object.serialize(&mut ser)?;
assert_eq!(buffer, b"---\nk: 107\n");
Ok(())
}
```
Closes #44.
=> Add a Serializer

src/ser.rs
```rust
use anyhow::Result;
use serde::Serialize;
use std::collections::BTreeMap;
fn main() -> Result<()> {
let mut buffer = Vec::new();
let mut ser = serde_yaml::Serializer::new(&mut buffer);
let mut object = BTreeMap::new();
object.insert("k", 107);
object.serialize(&mut ser)?;
object.insert("j", 106);
object.serialize(&mut ser)?;
assert_eq!(buffer, b"---\nk: 107\n...\n---\nj: 106\nk: 107\n");
Ok(())
}
```
=> Support multi-doc serialization

src/de.rs, src/error.rs
```rust
use anyhow::Result;
use serde::Deserialize;
use serde_yaml::Value;
fn main() -> Result<()> {
let input = "---\nk: 107\n...\n---\nj: 106\n";
for document in serde_yaml::Deserializer::from_str(input) {
let value = Value::deserialize(document)?;
println!("{:?}", value);
}
Ok(())
}
```
Closes #175.
=> Support multi-doc deserialization

README.md
Hi!
I just followed the installation instructions and the snippet in the README was actually failing 😅
=> Fix assert in README

src/value/mod.rs, tests/test_value.rs
I've taken the liberty of implementing `IntoDeserializer` for Value as mentioned in https://github.com/dtolnay/serde-yaml/issues/169.
I could use this functionality in my crates.
=> Add IntoDeserializer implementation to Value enum

src/ser.rs
I experienced bytes being silently dropped when serializing large objects to compressed files using `serde_yaml` and `flate2`/`bzip2`. I believe this PR will fix the issue, but I haven't tested it yet to confirm. Regardless, it's clear that this change is necessary so that `FmtToIoWriter` meets the contract of `std::fmt::Write`.
Previously, the implementation could silently fail to write some bytes. Now, the implementation should either write all the bytes or return an error.
The docs for [`std::fmt::Write::write_str`](https://doc.rust-lang.org/std/fmt/trait.Write.html#tymethod.write_str) say, "This method can only succeed if the entire string slice was successfully written, and this method will not return until all data has been written or an error occurs." So, `FmtToIoWriter::write_str` …
=> Fix FmtToIoWriter::write_str to call write_all

src/lib.rs, src/number.rs
The derived implementation previously had at least 2 problems:
- It was incompatible with the handwritten PartialEq impl. This definitely warrants a fix. It was possible in the case of NaNs for PartialEq to consider then equal while PartialOrd would consider them incomparable. This violates the following documented requirement of the PartialOrd trait in relation to PartialEq: *"`a == b` if and only if `partial_cmp(a, b) == Some(Equal)`"*.
- Positive integers would sort less than negative integers, which can be unexpected. It's unclear whether this matters to any real use case but we might as well fix it since it's easy.
=> Handwrite a better PartialOrd for Number

.github/workflows/ci.yml, Cargo.toml, src/lib.rs, src/mapping.rs, src/number.rs
IndexMap has equivalent guarantees as far as would be relevant to the serde_yaml API, and is actively maintained unlike LinkedHashMap.
The same switch in serde_json: https://github.com/serde-rs/json/pull/451.
=> Replace LinkedHashMap with IndexMap

src/de.rs, src/ser.rs, src/value/de.rs, tests/test_de.rs, tests/test_serde.rs
The oldest rustc that serde-yaml builds with is 1.38. The `u128` and `i128` types are supported by serde on rustc 1.26+ for non-emscripten targets, and 1.40+ for emscripten. I am skeptical that anybody targeting emscripten would be using either 1.38 or 1.39 compilers today in 2021 because the target has matured so much recently, so effectively nobody cares about the non-128 bit codepath.
=> Make 128 bit support unconditional

src/ser.rs, tests/test_serde.rs
This change adds explicit formatting for f32 to avoid artifacts when promoting to f64.
Fixes dtolnay/serde-yaml#213
=> Serialize f32

src/de.rs, tests/test_de.rs
Previously we'd treat values like `0127` as correctly a string not a number, per the YAML 1.2 spec. However that check did not kick in when there was a sign: `-0127` or `+0127`, and those would end up getting parsed as a base 10 number via u64::from_str or i64::from_str, which is not correct.
=> Treat YAML 1.1 style octals with sign as string, not base 10 number

Cargo.toml
`indexmap`'s use of `autocfg` doesn't always properly detect `std`, which is needed if you're using the default `S` hasher. The "indexmap/std" feature will explicitly force it on.
Fixes #229.
=> Explicitly enable indexmap/std

src/ser.rs
Without this method, in order to flush the writer between YAML documents, the user has to call `.into_inner()` to get the underlying writer, optionally write "...\n", call `.flush()` on the writer, and then construct a new `Serializer`.
=> Add .flush() method to Serializer

src/de.rs, src/lib.rs, src/loader.rs
This sets up for a refactor to move to an incremental loader, which will scan events from the YAML event stream only as the Deserializer reaches them, as opposed to all up front.
=> Extract Loader to separate module

src/de.rs, src/loader.rs
The idiom for iterating over documents in a single input is:
```rust
let de = serde_yaml::Deserializer::from_str(…);
for document in de {
let t = T::deserialize(document)?;
…
}
```
It's confusing to assign semantics to the following however, since YAML only has one level of documents; documents cannot be nested inside of other documents.
```rust
let de = serde_yaml::Deserializer::from_str(…);
for document in de {
for nested in document {
let t = T::deserialize(nested)?;
}
}
```
Previously this would do something confusing based on whether a `T` had been deserialized from `document` directly already or not. After this PR, `document` will always appear empty when iterated.
=> Disallow iterating Deserializers obtained from iteration

src/de.rs, src/loader.rs
The current yaml-rust backend can't produce these, but libyaml will be able to.
=> Store potentially non-utf8 for scalars

src/lib.rs, src/value/mod.rs
This matches the similar API of `serde_json::value`.
=> Make serde_yaml::value module public

src/de.rs, tests/test_de.rs
Previously serde_yaml would fail to take into account `0x`/`0o`/`0b` prefixes on 128-bit integers.
=> Revamp integer parsing

src/ser.rs
I am about to add some logic to detect strings that need surrounding quotes in order to roundtrip (`"true"` for example) and this change will help to only need that in one place.
=> Route variant name serialization through serialize_str

src/value/mod.rs, src/value/partial_eq.rs
This impl being handwritten was obsoleted by #64. Prior to that PR it was necessary in order to handle the F64 variant specially.
=> Replace handwritten PartialEq with derive for Value

src/de.rs, src/error.rs, tests/test_error.rs
We cap the number of alias jumps to 100&times; the number of events in the input stream.
Closes #53.
=> Add a billion laughs mitigation

src/de.rs, src/error.rs, src/ser.rs, tests/test_error.rs
I guess we'll want to implement this using YAML's binary type, per #91. Whatever it's currently doing is not right; delete for now.
=> Disable bytes serialization and deserialization

src/value/debug.rs, src/value/mod.rs, tests/test_value.rs
YAML input:
```yaml
Null: ~
Bool: true
Number: 1
String: ...
Sequence:
- true
EmptySequence: []
Mapping:
k: v
EmptyMapping: {}
Tagged: !tag true
```
Before:
```rust
Mapping(
Mapping {
map: {
String(
"Null",
): Null,
String(
"Bool",
): Bool(
true,
),
String(
"Number",
): Number(
PosInt(
1,
),
),
String(
"String",
): String(
"...",
),
String(
"Sequence",
): Sequence(
[
Bool(
true,
),
],
),
String(
"EmptySequence",
): Sequence(
[],
),
String(
"Mapping",
): Mapping(
Mapping {
map: {
String(
"k",
): String(
"v",
),
},
},
),
String(
"EmptyMapping",
): Mapping(
Mapping {
map: {},
},
),
String(
"Tagged",
): Tagged(
TaggedValue {
tag: !tag,
value: Bool(
true,
),
},
),
},
},
)
```
After:
```rust
Mapping {
"Null": Null,
"Bool": Bool(true),
"Number": Number(1),
"String": String("..."),
"Sequence": …
```
=> Handwrite a better Debug for Value

src/de.rs, src/lib.rs, tests/test_de.rs
No longer necessary since the `Deserializer` has been made public. For example `serde_yaml::from_str_seed(yaml, seed)` is just `seed.deserialize(serde_yaml::Deserializer::from_str(yaml))`.
=> Remove seed module and functions

src/lib.rs, src/ser.rs
I don't know of this being useful. Directly use `to_writer` instead if you need bytes for I/O, or  use `to_string` + https://doc.rust-lang.org/std/string/struct.String.html#method.into_bytes if you really need the `Vec<u8>`.
=> Remove serde_yaml::to_vec

src/de.rs, src/libyaml/parser.rs, tests/test_error.rs
=> Fix unreachable code panic on scan error

src/error.rs, tests/test_error.rs
This matches the approach used for serde_json's errors, and is a good fit for the formatting that appears when `.unwrap()` is used.
**Before:**
```rust
UnknownAnchor(
Mark {
line: 1,
column: 5,
},
)
```
**After:**
```rust
Error("unknown anchor", line: 1, column: 5)
```
=> Improve Debug representation of Error

src/lib.rs, src/with.rs
```rust
#[derive(Serialize, Deserialize)]
struct Struct {
#[serde(with = "serde_yaml::with::singleton_map")]
e: Enum,
}
```
will represent that field as a 1-element map `variant: {contents}` instead of the default tag-based representation `!variant {contents}`.
=> Add a singleton_map module for serde's 'with' attribute

src/mapping.rs, tests/test_error.rs
=> Error on duplicate key when deserializing Mapping

src/value/tagged.rs
=> Implement Display trait for serde_yaml::value::tagged::Tag

src/de.rs, src/value/de.rs
There should be no observable difference in behavior. Having a separate deserialize_struct implementation was obsoleted by 395a0eb1260a8335c1d3712975d2911cddfcd643.
=> Implement deserialize_struct via deserialize_map

src/de.rs, src/value/de.rs, tests/test_de.rs, tests/test_error.rs
=> Deserialize empty plain scalar to an empty map or seq

src/libyaml/emitter.rs, tests/test_serde.rs
For strings that already contain newlines, serde_yaml will preserve them (since #270). For strings that do not already contain newlines I don't think serde_yaml should add newlines to them. Closes #321.
=> Set width=-1 on libyaml emitter

src/de.rs, tests/test_de.rs
=> Support deserializing tagged literal scalar into primitive

src/de.rs, tests/test_de.rs, tests/test_value.rs
Closes #329.
See https://yaml.org/spec/1.2.2/#1032-tag-resolution.
=> Add some null and boolean representations from YAML 1.2

src/error.rs
Fixes #359.
The same code in the issue now produces:
```console
Error: bad read
Caused by:
timed out waiting on channel
```
=> Fix message duplication between error Display and source()

.github/workflows/ci.yml, Cargo.toml
Release notes: https://github.com/bluss/indexmap/blob/2.0.0/RELEASES.md
=> Update indexmap dependency to version 2

src/de.rs, src/error.rs, src/number.rs, tests/test_de.rs
=> Implement FromStr for serde_yaml::Number

src/ser.rs, tests/test_serde.rs
=> Use quoted style for strings consisting of digits with leading zero

src/de.rs, tests/test_de.rs, tests/test_value.rs
I learned in https://github.com/rust-lang/miri/issues/3139 that the sign of f64::NAN is not specified.
=> Ensure that .nan deserialization produces positive NaN

Cargo.toml, tests/test_de.rs
#392 covered the case of deserializing to `serde_yaml::Number` only.
For primitives, https://github.com/serde-rs/serde/pull/2637 is necessary.
=> Add test of NaN sign when deserializing to primitive

src/number.rs
Previously the `f32 as f64` would produce a nondeterministic sign, as I found out in https://github.com/rust-lang/miri/issues/3139. This would then get leaked by `as_f64()` or by serialization of the `Number`. It doesn't make a difference when serializing to YAML, but we support serializing `serde_yaml::Number` to TOML and other formats, where it does.
YAML only has one NaN, so even negative NaNs serialize to `.nan` in YAML. It seems fine to discard the original sign in `serde_yaml::Number` too.
=> Deterministically destroy sign of NaN when converted to Number

src/lib.rs, src/libyaml/emitter.rs, src/libyaml/error.rs, src/libyaml/parser.rs
This is allow-by-default for now in 2021 edition, but will become warn-by-default in 2024 edition.
=> Turn on deny(unsafe_op_in_unsafe_fn)
