src/de.rs
tests/de.rs

Deserialize missing Option to None

---

yaml/src/de.rs
yaml/src/error.rs
yaml/src/ser.rs
yaml_tests/tests/test_error.rs
yaml_tests/tests/test_serde.rs

Unit variants can be serialized/deserialized as strings

---

yaml/Cargo.toml
yaml/src/de.rs
yaml/src/forward.rs
yaml/src/lib.rs
yaml/src/ser.rs
yaml/src/value.rs
yaml_tests/Cargo.toml

easy peasy xD I think it's actually cleaner than before

serde push-serialization

---

yaml/src/de.rs

Deserialize real numbers as f64 instead of str

---

yaml/Cargo.toml
yaml/src/lib.rs
yaml/src/value.rs
yaml_tests/tests/test_serde.rs

Serializable serde_yaml::Value

---

yaml/Cargo.toml

Just for the sake of having less versions of the same lib in one of my projects :)

Update dtoa to 0.3

---

yaml/src/de.rs
yaml/src/ser.rs
yaml_tests/tests/test_serde.rs

Correctly serialize large u64 values (fixes #34)

---

src/lib.rs
src/value.rs

Copypasta from serde_json but with s/array/sequence :)

Implement fancy indexing

---

src/value.rs

Makes it easier to create YAML values on the fly.

Implement a bunch of conversion traits

---

src/value.rs

Oh, you thought I was done? ;)

Add some more PartialEq impls

---

src/de.rs
src/value/de.rs

Related to #95. This is around 30% improvement in compile time on my use of serde_yaml.
Same idea as https://github.com/serde-rs/json/pull/389.

Implement all the deserializer hints

---

src/ser.rs
src/value/mod.rs
tests/test_serde.rs

Ensure consistent output when serializing through Value

---

src/lib.rs
src/mapping.rs

Make mapping module public

---

fuzz/.gitignore
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzz_from_slice.rs

Initial fuzzing setup for integration with OSS-Fuzz. The fuzzer setup is inspired by [rust-fuzz](https://github.com/rust-fuzz)

Added initial fuzzing setup.

---

src/de.rs
src/lib.rs

```rust
use anyhow::Result;
use serde::Deserialize;
use serde_yaml::Value;
fn main() -> Result<()> {
let input = "---\nk: 107\n";
let de = serde_yaml::Deserializer::from_str(input);
let value = Value::deserialize(de)?;
println!("{:?}", value);
Ok(())
}
```
Closes #44.

Add a Deserializer

---

src/error.rs

To be used in multi-doc deserialization.

Add an error variant with shared ownership

---

src/mapping.rs

Mostly copied from serde_json...
Closes #58.

Add an Entry API for Mapping

---

src/de.rs

`Deserializer`'s `input` field already contains a `Box<dyn Read>` so it is already not `Send` nor `Sync` regardless of the things touched here, and nobody has complained so far.
We can't easily switch to `Box<dyn Read + Send + Sync>` because `serde_yaml::Deserializer::from_reader` doesn't have those bounds, so I'm not sure what we would do if someone really needs this on multiple threads.

Replace Arc->Rc, AtomicUsize->Cell

---

src/de.rs
src/loader.rs

Previously, these two programs would (confusingly) do different things:
```rust
let mut de = serde_yaml::Deserializer::from_str("0");
let document1 = de.next().unwrap();
let _ = Value::deserialize(document1).unwrap();
let document2 = de.next().unwrap(); // None
let _ = Value::deserialize(document2).unwrap();
```
```rust
let mut de = serde_yaml::Deserializer::from_str("0");
let document1 = de.next().unwrap();
let document2 = de.next().unwrap(); // Some
let _ = Value::deserialize(document1).unwrap();
let _ = Value::deserialize(document2).unwrap();
```
That doesn't make sense; there is only one document in the YAML input regardless. This PR fixes `.next()` to reflect the actual number of documents in the input, regardless of where (or even if) the caller deserializes anything from those …

Give each document an independent position counter

---

src/loader.rs

This makes it possible to convert into a streaming parser in an upcoming PR.

Switch to parser's `next` instead of `load`

---

src/value/mod.rs
src/value/ser.rs

Equivalent to https://docs.rs/serde_json/latest/serde_json/value/struct.Serializer.html.

Add a Serializer to serialize directly to Value

---

tests/test_de.rs

Add a bunch more not-number test cases

---

src/number.rs
src/value/index.rs
src/value/mod.rs

Eliminate hidden yaml function from code examples in docs

---

src/value/de.rs
src/value/tagged.rs
tests/test_de.rs
tests/test_serde.rs

Implement Deserializer for &Value

---

src/value/partial_eq.rs

Remove wrong direction PartialEq impls

---

Cargo.toml
src/mapping.rs

- https://docs.rs/indexmap/1/indexmap/map/struct.IndexMap.html#method.remove_entry
- https://docs.rs/indexmap/1/indexmap/map/struct.IndexMap.html#method.retain
- https://docs.rs/indexmap/1/indexmap/map/struct.IndexMap.html#method.keys
- https://docs.rs/indexmap/1/indexmap/map/struct.IndexMap.html#method.into_keys
- https://docs.rs/indexmap/1/indexmap/map/struct.IndexMap.html#method.values
- https://docs.rs/indexmap/1/indexmap/map/struct.IndexMap.html#method.values_mut
- https://docs.rs/indexmap/1/indexmap/map/struct.IndexMap.html#method.into_values
- https://docs.rs/indexmap/1/indexmap/map/struct.OccupiedEntry.html#method.remove_entry
- https://docs.rs/indexmap/1/indexmap/map/struct.VacantEntry.html#method.into_key

Expose more APIs from indexmap on Mapping

---

src/value/tagged.rs

```rust
use serde_yaml::value::TaggedValue;
use std::collections::BTreeMap;
fn main() {
let yaml = "
scalar: !Thing x
sequence_flow: !Thing [first]
sequence_block: !Thing
- first
mapping_flow: !Thing {k: v}
mapping_block: !Thing
k: v
";
let data: BTreeMap<String, TaggedValue> = serde_yaml::from_str(yaml).unwrap();
assert!(data["scalar"].tag == "Thing");
assert!(data["sequence_flow"].tag == "Thing");
assert!(data["sequence_block"].tag == "Thing");
assert!(data["mapping_flow"].tag == "Thing");
assert!(data["mapping_block"].tag == "Thing");
// The leading '!' in tags are not significant. The following is also true.
assert!(data["scalar"].tag == "!Thing");
}
```

Implement Deserialize for TaggedValue

---

src/ser.rs
tests/test_serde.rs

Fix tag not getting serialized in certain map values

---

src/value/ser.rs
src/value/tagged.rs
tests/test_value.rs

Fix serialization of TaggedValue in to_value

---

src/value/tagged.rs

They both already implement `EnumAccess` so these impls are straightforward.
This came up in https://github.com/dtolnay/serde-yaml/issues/338.

Implement Deserializer for TaggedValue and &TaggedValue

---

Cargo.toml
tests/test_serde.rs

https://github.com/dtolnay/unsafe-libyaml/pull/20

Adding support for emitting Unicode characters over codepoint U+FFFF
